pc = require('./core').pc;
require('./color');
require('./guid');
require('./time');
require('./uri');
require('./log');
require('./inheritance');
require('./path');
require('./string');
require('./debug');
require('./events');
require('./tags');
require('./object-pool');
